version: "3.8"

services:
  pg:
    image: postgres
    volumes:
      - type: volume
        source: travelru
        target: /var/lib/postgresql/data
    env_file:
      - .env-postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./travelRu/:/code
    ports:
      - "8000:8000"
    depends_on:
      - pg
volumes:
  travelru:

