# Generated by Django 3.2 on 2022-07-18 18:33
from django.contrib.auth.models import User
from django.db import migrations


def add_default_user(apps, schema_editor):
    # User = apps.get_model('my_travel', 'User')
    user = User.objects.create_user(username='guest', password='fdsa4321')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel', '0002_auto_20220717_0217'),
    ]

    operations = [
        migrations.RunPython(add_default_user),
    ]
