# Generated by Django 3.2 on 2022-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hotel_city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
