# Generated by Django 3.2 on 2022-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel', '0005_item_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nights',
            field=models.IntegerField(null=True),
        ),
    ]
