# Generated by Django 3.2 on 2022-07-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_travel', '0006_hotel_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='item_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_travel.item'),
        ),
    ]
