# Generated by Django 3.2 on 2022-07-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_travel', '0008_auto_20220721_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avia',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_travel.item'),
        ),
    ]
