"""
configuration
"""
# flake8: noqa
# pylint: skip-file
IATA = [
    {'city_code': 'ЭГТ', 'country_code': 'RU', 'name_translations': {'en': 'Zaliv Kresta'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 66.35833, 'lon': 179.11}, 'name': 'Залив Креста', 'code': 'ЭГТ',
     'iata_type': 'airport', 'city_name': 'Эгвекинот'},
    {'city_code': 'ABA', 'country_code': 'RU', 'name_translations': {'en': 'Abakan Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 53.716667, 'lon': 91.5},
     'name': 'Абакан', 'code': 'ABA', 'iata_type': 'airport', 'city_name': 'Абакан'},
    {'city_code': 'PES', 'country_code': 'RU', 'name_translations': {'en': 'Petrozavodsk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 61.683334, 'lon': 34.333332},
     'name': 'Бесовец', 'code': 'PES', 'iata_type': 'airport', 'city_name': 'Петрозаводск'},
    {'city_code': 'OVB', 'country_code': 'RU', 'name_translations': {'en': 'Novosibirsk Tolmachevo Airport'},
     'time_zone': 'Asia/Phnom_Penh', 'flightable': 'true', 'coordinates': {'lat': 55.00901, 'lon': 82.667},
     'name': 'Толмачёво', 'code': 'OVB', 'iata_type': 'airport', 'city_name': 'Новосибирск'},
    {'city_code': 'NGK', 'country_code': 'RU', 'name_translations': {'en': 'Nogliki Airport'},
     'time_zone': 'Asia/Sakhalin', 'flightable': 'true', 'coordinates': {'lat': 51.8, 'lon': 143.16667},
     'name': 'Ноглики', 'code': 'NGK', 'iata_type': 'airport', 'city_name': 'Ноглики'},
    {'city_code': 'KUF', 'country_code': 'RU', 'name_translations': {'en': 'Kurumoch International Airport'},
     'time_zone': 'Europe/Samara', 'flightable': 'true', 'coordinates': {'lat': 53.50782, 'lon': 50.14742},
     'name': 'Курумоч', 'code': 'KUF', 'iata_type': 'airport', 'city_name': 'Самара'},
    {'city_code': 'ЗЕЯ', 'country_code': 'RU', 'name_translations': {'en': 'Zeja'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 53.689724, 'lon': 127.092224}, 'name': 'Зея', 'code': 'ЗЕЯ',
     'iata_type': 'airport', 'city_name': 'Зея'},
    {'city_code': 'NNM', 'country_code': 'RU', 'name_translations': {'en': 'Naryan-Mar Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 67.61667, 'lon': 53.15},
     'name': 'Нарьян-Мар', 'code': 'NNM', 'iata_type': 'airport', 'city_name': 'Нарьян-Мар'},
    {'city_code': 'СОЛ', 'country_code': 'RU', 'name_translations': {'en': 'Stary Oskol'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 51.328335, 'lon': 37.766666}, 'name': 'Старый Оскол', 'code': 'СОЛ',
     'iata_type': 'airport', 'city_name': 'Старый Оскол'},
    {'city_code': 'KYZ', 'country_code': 'RU', 'name_translations': {'en': 'Kyzyl Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 51.7, 'lon': 94.46667},
     'name': 'Кызыл', 'code': 'KYZ', 'iata_type': 'airport', 'city_name': 'Кызыл'},
    {'city_code': 'JOK', 'country_code': 'RU', 'name_translations': {'en': 'Yoshkar-Ola Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 56.716667, 'lon': 47.9},
     'name': 'Йошкар-Ола', 'code': 'JOK', 'iata_type': 'airport', 'city_name': 'Йошкар-Ола'},
    {'city_code': 'ARH', 'country_code': 'RU', 'name_translations': {'en': 'Talagi Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 64.594795, 'lon': 40.711903},
     'name': 'Талаги', 'code': 'ARH', 'iata_type': 'airport', 'city_name': 'Архангельск'},
    {'city_code': 'ARH', 'country_code': 'RU', 'name_translations': {'en': 'Vaskovo'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 64.441666, 'lon': 40.422222}, 'name': 'Васьково', 'code': 'ВСЬ',
     'iata_type': 'airport', 'city_name': 'Архангельск'},
    {'city_code': 'ULY', 'country_code': 'RU', 'name_translations': {'en': 'Baratayevka'}, 'time_zone': 'Europe/Samara',
     'flightable': 'true', 'coordinates': {'lat': 54.268333, 'lon': 48.226665}, 'name': 'Баратаевка', 'code': 'ULV',
     'iata_type': 'airport', 'city_name': 'Ульяновск'},
    {'city_code': 'UTS', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Tsilma'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 65.433334, 'lon': 52.2}, 'name': 'Каменогорск (Усть-Цильма)',
     'code': 'UTS', 'iata_type': 'airport', 'city_name': 'Усть-Цильма'},
    {'city_code': 'PEX', 'country_code': 'RU', 'name_translations': {'en': 'Pechora Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 65.11667, 'lon': 57.13333},
     'name': 'Печора', 'code': 'PEX', 'iata_type': 'airport', 'city_name': 'Печора'},
    {'city_code': 'ЖЕЗ', 'country_code': 'RU', 'name_translations': {'en': 'Zheleznogorsk'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 57.617626, 'lon': 79.46004},
     'name': 'Железногорск', 'code': 'ЖЕЗ', 'iata_type': 'airport', 'city_name': 'Железногорск'},
    {'city_code': 'MQJ', 'country_code': 'RU', 'name_translations': {'en': 'Moma'}, 'time_zone': 'Asia/Srednekolymsk',
     'flightable': 'true', 'coordinates': {'lat': 66.450874, 'lon': 143.26251}, 'name': 'Мома', 'code': 'МОМ',
     'iata_type': 'airport', 'city_name': 'Хонуу'},
    {'city_code': 'MQJ', 'country_code': 'RU', 'name_translations': {'en': 'Moma'}, 'time_zone': 'Asia/Srednekolymsk',
     'flightable': 'true', 'coordinates': {'lat': 66.45583, 'lon': 143.25305}, 'name': 'Мома', 'code': 'MQJ',
     'iata_type': 'airport', 'city_name': 'Хонуу'},
    {'city_code': 'KRO', 'country_code': 'RU', 'name_translations': {'en': 'Kurgan Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 55.433334, 'lon': 65.3},
     'name': 'Курган', 'code': 'KRO', 'iata_type': 'airport', 'city_name': 'Курган'},
    {'city_code': 'BAX', 'country_code': 'RU', 'name_translations': {'en': 'Barnaul Airport'},
     'time_zone': 'Asia/Novokuznetsk', 'flightable': 'true', 'coordinates': {'lat': 53.361088, 'lon': 83.547646},
     'name': 'Михайловка', 'code': 'BAX', 'iata_type': 'airport', 'city_name': 'Барнаул'},
    {'city_code': 'CSY', 'country_code': 'RU', 'name_translations': {'en': 'Cheboksary Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 56.13333, 'lon': 47.266666},
     'name': 'Чебоксары', 'code': 'CSY', 'iata_type': 'airport', 'city_name': 'Чебоксары'},
    {'city_code': 'VOG', 'country_code': 'RU', 'name_translations': {'en': 'Volgograd International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 48.792, 'lon': 44.354805},
     'name': 'Гумрак', 'code': 'VOG', 'iata_type': 'airport', 'city_name': 'Волгоград'},
    {'city_code': 'VOZ', 'country_code': 'RU', 'name_translations': {'en': 'Voronezh Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 51.812355, 'lon': 39.226997},
     'name': 'Чертовицкое', 'code': 'VOZ', 'iata_type': 'airport', 'city_name': 'Воронеж'},
    {'city_code': 'ТИЛ', 'country_code': 'RU', 'name_translations': {'en': 'Tilichiki'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 60.385277, 'lon': 166.02556}, 'name': 'Тиличики', 'code': 'ТИЛ',
     'iata_type': 'airport', 'city_name': 'Тиличики'},
    {'city_code': 'МАМ', 'country_code': 'RU', 'name_translations': {'en': 'Mama'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 58.3, 'lon': 112.88333}, 'name': 'Мама', 'code': 'МАМ',
     'iata_type': 'airport', 'city_name': 'Мама'},
    {'city_code': 'ОСУ', 'country_code': 'RU', 'name_translations': {'en': 'Omsukchan'}, 'time_zone': 'Asia/Magadan',
     'flightable': 'true', 'coordinates': {'lat': 62.458332, 'lon': 155.74556}, 'name': 'Омсукчан', 'code': 'ОСУ',
     'iata_type': 'airport', 'city_name': 'Омсукчан'},
    {'city_code': 'STW', 'country_code': 'RU', 'name_translations': {'en': 'Stavropol Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 45.333332, 'lon': 42.00833},
     'name': 'Ставрополь', 'code': 'STW', 'iata_type': 'airport', 'city_name': 'Ставрополь'},
    {'city_code': 'TYD', 'country_code': 'RU', 'name_translations': {'en': 'Tynda Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 55.283333, 'lon': 124.73333},
     'name': 'Тында', 'code': 'TYD', 'iata_type': 'airport', 'city_name': 'Тында'},
    {'city_code': 'DHG', 'country_code': 'RU', 'name_translations': {'en': 'Dalnegorsk'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 44.55892, 'lon': 135.49123},
     'name': 'Дальнегорск', 'code': 'DHG', 'iata_type': 'airport', 'city_name': 'Дальнегорск'},
    {'city_code': 'DHG', 'country_code': 'RU', 'name_translations': {'en': 'Dalnegorsk'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 44.55, 'lon': 135.56667},
     'name': 'Дальнегорск', 'code': 'ДНГ', 'iata_type': 'airport', 'city_name': 'Дальнегорск'},
    {'city_code': 'NUX', 'country_code': 'RU', 'name_translations': {'en': 'Novy Urengoy Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 66.07335, 'lon': 76.522835},
     'name': 'Новый Уренгой', 'code': 'NUX', 'iata_type': 'airport', 'city_name': 'Новый Уренгой'},
    {'city_code': 'ССМ', 'country_code': 'RU', 'name_translations': {'en': 'Susuman'}, 'time_zone': 'Asia/Magadan',
     'flightable': 'true', 'coordinates': {'lat': 62.76722, 'lon': 148.1461}, 'name': 'Сусуман', 'code': 'ССМ',
     'iata_type': 'airport', 'city_name': 'Сусуман'},
    {'city_code': 'IRM', 'country_code': 'RU', 'name_translations': {'en': 'Igrim'}, 'time_zone': 'Asia/Yekaterinburg',
     'flightable': 'true', 'coordinates': {'lat': 63.200756, 'lon': 64.433945}, 'name': 'Игрим', 'code': 'IRM',
     'iata_type': 'airport', 'city_name': 'Игрим'},
    {'city_code': 'UFA', 'country_code': 'RU', 'name_translations': {'en': 'Ufa International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 54.565403, 'lon': 55.884544},
     'name': 'Уфа', 'code': 'UFA', 'iata_type': 'airport', 'city_name': 'Уфа'},
    {'city_code': 'UUD', 'country_code': 'RU', 'name_translations': {'en': 'Ulan-Ude Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 51.833332, 'lon': 107.5},
     'name': 'Байкал', 'code': 'UUD', 'iata_type': 'airport', 'city_name': 'Улан-Удэ'},
    {'city_code': 'KPW', 'country_code': 'RU', 'name_translations': {'en': 'Keperveyem'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 67.84611, 'lon': 166.13722}, 'name': 'Кепервеем', 'code': 'КПМ',
     'iata_type': 'airport', 'city_name': 'Кепервеем'},
    {'city_code': 'KPW', 'country_code': 'RU', 'name_translations': {'en': 'Keperveyem Airport'},
     'time_zone': 'Asia/Kamchatka', 'flightable': 'true', 'coordinates': {'lat': 67.84611, 'lon': 166.13722},
     'name': 'Кепервеем', 'code': 'KPW', 'iata_type': 'airport', 'city_name': 'Кепервеем'},
    {'city_code': 'BQJ', 'country_code': 'RU', 'name_translations': {'en': 'Batagay'}, 'time_zone': 'Asia/Vladivostok',
     'flightable': 'true', 'coordinates': {'lat': 67.655, 'lon': 134.64166}, 'name': 'Батагай', 'code': 'BQJ',
     'iata_type': 'airport', 'city_name': 'Батагай'},
    {'city_code': 'KLF', 'country_code': 'RU', 'name_translations': {'en': 'Grabtsevo Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 54.546665, 'lon': 36.36889},
     'name': 'Грабцево', 'code': 'KLF', 'iata_type': 'airport', 'city_name': 'Калуга'},
    {'city_code': 'PYJ', 'country_code': 'RU', 'name_translations': {'en': 'Polyarnyj Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 66.416664, 'lon': 112.05},
     'name': 'Полярный', 'code': 'PYJ', 'iata_type': 'airport', 'city_name': 'Удачный'},
    {'city_code': 'ХРП', 'country_code': 'RU', 'name_translations': {'en': 'Kherpuchi'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 52.975, 'lon': 138.81667},
     'name': 'Херпучи', 'code': 'ХРП', 'iata_type': 'airport', 'city_name': 'Херпучи'},
    {'city_code': 'BTK', 'country_code': 'RU', 'name_translations': {'en': 'Bratsk Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 56.36667, 'lon': 101.816666},
     'name': 'Братск', 'code': 'BTK', 'iata_type': 'airport', 'city_name': 'Братск'},
    {'city_code': 'OMS', 'country_code': 'RU', 'name_translations': {'en': 'Omsk Airport'}, 'time_zone': 'Asia/Omsk',
     'flightable': 'true', 'coordinates': {'lat': 54.957455, 'lon': 73.3167}, 'name': 'Омск', 'code': 'OMS',
     'iata_type': 'airport', 'city_name': 'Омск'},
    {'city_code': 'БНГ', 'country_code': 'RU', 'name_translations': {'en': 'Beringovskiy'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 63.020832, 'lon': 179.29056}, 'name': 'Филиал ФКП "А/П Чукотки"',
     'code': 'БНГ', 'iata_type': 'airport', 'city_name': 'Беринговский'},
    {'city_code': 'IKT', 'country_code': 'RU', 'name_translations': {'en': 'Irkutsk International Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 52.273308, 'lon': 104.35607},
     'name': 'Иркутск', 'code': 'IKT', 'iata_type': 'airport', 'city_name': 'Иркутск'},
    {'city_code': 'CSH', 'country_code': 'RU', 'name_translations': {'en': 'Solovky'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 65.02944, 'lon': 35.733334}, 'name': 'Соловки', 'code': 'CSH',
     'iata_type': 'airport', 'city_name': 'Соловецкий'},
    {'city_code': 'ТЬК', 'country_code': 'RU', 'name_translations': {'en': 'Tolka'}, 'time_zone': 'Asia/Yekaterinburg',
     'flightable': 'true', 'coordinates': {'lat': 63.986946, 'lon': 82.05139}, 'name': 'Толька', 'code': 'ТЬК',
     'iata_type': 'airport', 'city_name': 'Толька'},
    {'city_code': 'UUS', 'country_code': 'RU', 'name_translations': {'en': 'Yuzhno-Sakhalinsk Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 46.966667, 'lon': 142.75},
     'name': 'Южно-Сахалинск', 'code': 'UUS', 'iata_type': 'airport', 'city_name': 'Южно-Сахалинск'},
    {'city_code': 'ТИГ', 'country_code': 'RU', 'name_translations': {'en': 'Tigil'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 57.783333, 'lon': 158.72667}, 'name': 'Тигиль', 'code': 'ТИГ',
     'iata_type': 'airport', 'city_name': 'Тигиль'},
    {'city_code': 'ОЗР', 'country_code': 'RU', 'name_translations': {'en': 'Ozernaya'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 51.5, 'lon': 156.58333}, 'name': 'Озерная', 'code': 'ОЗР',
     'iata_type': 'airport', 'city_name': 'Озерная'},
    {'city_code': 'ЧАР', 'country_code': 'RU', 'name_translations': {'en': 'Chara'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 56.914722, 'lon': 118.270836}, 'name': 'Чара', 'code': 'ЧАР',
     'iata_type': 'airport', 'city_name': 'Чара'},
    {'city_code': 'ЗЛА', 'country_code': 'RU', 'name_translations': {'en': 'Lavrentija'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 65.583336, 'lon': 171.01334}, 'name': 'Лаврентия', 'code': 'ЗЛА',
     'iata_type': 'airport', 'city_name': 'Залив Лаврентия'},
    {'city_code': 'МИЛ', 'country_code': 'RU', 'name_translations': {'en': 'Manily'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 62.485832, 'lon': 165.3364}, 'name': 'Манилы', 'code': 'МИЛ',
     'iata_type': 'airport', 'city_name': 'Манилы'},
    {'city_code': 'СБО', 'country_code': 'RU', 'name_translations': {'en': 'Sobolevo'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 54.306946, 'lon': 155.97417}, 'name': 'Соболево', 'code': 'СБО',
     'iata_type': 'airport', 'city_name': 'Соболево'},
    {'city_code': 'CEE', 'country_code': 'RU', 'name_translations': {'en': 'Cherepovets Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 59.283333, 'lon': 38.066666},
     'name': 'Череповец', 'code': 'CEE', 'iata_type': 'airport', 'city_name': 'Череповец'},
    {'city_code': 'НЛН', 'country_code': 'RU', 'name_translations': {'en': 'Nelkan'}, 'time_zone': 'Asia/Vladivostok',
     'flightable': 'true', 'coordinates': {'lat': 57.641666, 'lon': 136.16167}, 'name': 'Нелькан', 'code': 'НЛН',
     'iata_type': 'airport', 'city_name': 'Нелькан'},
    {'city_code': 'ТИО', 'country_code': 'RU', 'name_translations': {'en': 'Taksimo'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 56.361668, 'lon': 114.92722}, 'name': 'Таксимо', 'code': 'ТИО',
     'iata_type': 'airport', 'city_name': 'Таксимо'},
    {'city_code': 'HTG', 'country_code': 'RU', 'name_translations': {'en': 'Hatanga Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 71.96667, 'lon': 102.5},
     'name': 'Хатанга', 'code': 'HTG', 'iata_type': 'airport', 'city_name': 'Хатанга'},
    {'city_code': 'PKV', 'country_code': 'RU', 'name_translations': {'en': 'Pskov Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 57.816666, 'lon': 28.3},
     'name': 'Кресты', 'code': 'PKV', 'iata_type': 'airport', 'city_name': 'Псков'},
    {'city_code': 'TOF', 'country_code': 'RU', 'name_translations': {'en': 'Tomsk Airport'},
     'time_zone': 'Asia/Novokuznetsk', 'flightable': 'true', 'coordinates': {'lat': 56.5, 'lon': 84.96667},
     'name': 'Богашёво', 'code': 'TOF', 'iata_type': 'airport', 'city_name': 'Томск'},
    {'city_code': 'PEE', 'country_code': 'RU', 'name_translations': {'en': 'Perm International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 57.920025, 'lon': 56.01918},
     'name': 'Большое Савино', 'code': 'PEE', 'iata_type': 'airport', 'city_name': 'Пермь'},
    {'city_code': 'VYI', 'country_code': 'RU', 'name_translations': {'en': 'Vilyuisk'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 63.75639, 'lon': 121.69306}, 'name': 'Вилюйск', 'code': 'VYI',
     'iata_type': 'airport', 'city_name': 'Вилюйск'},
    {'city_code': 'NOZ', 'country_code': 'RU', 'name_translations': {'en': 'Novokuznetsk Airport'},
     'time_zone': 'Asia/Novokuznetsk', 'flightable': 'true', 'coordinates': {'lat': 53.75, 'lon': 87.166664},
     'name': 'Спиченково', 'code': 'NOZ', 'iata_type': 'airport', 'city_name': 'Новокузнецк'},
    {'city_code': 'ВРЯ', 'country_code': 'RU', 'name_translations': {'en': 'Vanavara'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 60.356667, 'lon': 102.31}, 'name': 'Ванавара', 'code': 'ВРЯ',
     'iata_type': 'airport', 'city_name': 'Ванавара'},
    {'city_code': 'MCX', 'country_code': 'RU', 'name_translations': {'en': 'Makhachkala Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 42.82095, 'lon': 47.65611},
     'name': 'Уйташ', 'code': 'MCX', 'iata_type': 'airport', 'city_name': 'Махачкала'},
    {'city_code': 'EYK', 'country_code': 'RU', 'name_translations': {'en': 'Beloyarsky Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 63.696682, 'lon': 66.70121},
     'name': 'Белоярский', 'code': 'EYK', 'iata_type': 'airport', 'city_name': 'Белоярский'},
    {'city_code': 'SWV', 'country_code': 'RU', 'name_translations': {'en': 'Severo-Evensk Airport'},
     'time_zone': 'Asia/Magadan', 'flightable': 'true', 'coordinates': {'lat': 61.924442, 'lon': 159.23111},
     'name': 'Эвенск', 'code': 'SWV', 'iata_type': 'airport', 'city_name': 'Эвенск'},
    {'city_code': 'KRR', 'country_code': 'RU', 'name_translations': {'en': 'Krasnodar International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 45.034138, 'lon': 39.139004},
     'name': 'Пашковский', 'code': 'KRR', 'iata_type': 'airport', 'city_name': 'Краснодар'},
    {'city_code': 'ООЛ', 'country_code': 'RU', 'name_translations': {'en': 'Omolon'}, 'time_zone': 'Asia/Magadan',
     'flightable': 'true', 'coordinates': {'lat': 65.238335, 'lon': 160.54195}, 'name': 'Омолон', 'code': 'ООЛ',
     'iata_type': 'airport', 'city_name': 'Омолон'},
    {'city_code': 'КСЧ', 'country_code': 'RU', 'name_translations': {'en': 'Krasny Chikoy'}, 'time_zone': 'Asia/Chita',
     'flightable': 'true', 'coordinates': {'lat': 50.370834, 'lon': 108.76444}, 'name': 'Красный Чикой', 'code': 'КСЧ',
     'iata_type': 'airport', 'city_name': 'Красный Чикой'},
    {'city_code': 'UKX', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Kut Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 56.85, 'lon': 105.73333},
     'name': 'Усть-Кут', 'code': 'UKX', 'iata_type': 'airport', 'city_name': 'Усть-Кут'},
    {'city_code': 'NYM', 'country_code': 'RU', 'name_translations': {'en': 'Nadym Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 65.48333, 'lon': 72.71667},
     'name': 'Надым', 'code': 'NYM', 'iata_type': 'airport', 'city_name': 'Надым'},
    {'city_code': 'HTA', 'country_code': 'RU', 'name_translations': {'en': 'Chita Airport'}, 'time_zone': 'Asia/Chita',
     'flightable': 'true', 'coordinates': {'lat': 52.033333, 'lon': 113.3}, 'name': 'Кадала', 'code': 'HTA',
     'iata_type': 'airport', 'city_name': 'Чита'},
    {'city_code': 'IWA', 'country_code': 'RU', 'name_translations': {'en': 'Ivanovo Yuzhny Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 56.942955, 'lon': 40.944546},
     'name': 'Иваново', 'code': 'IWA', 'iata_type': 'airport', 'city_name': 'Иваново'},
    {'city_code': 'ПАН', 'country_code': 'RU', 'name_translations': {'en': 'Palana'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 59.081665, 'lon': 159.88861}, 'name': 'Палана', 'code': 'ПАН',
     'iata_type': 'airport', 'city_name': 'Палана'},
    {'city_code': 'GYG', 'country_code': 'RU', 'name_translations': {'en': 'Magan'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 62.10327, 'lon': 129.55006}, 'name': 'Маган', 'code': 'GYG',
     'iata_type': 'airport', 'city_name': 'Маган'},
    {'city_code': 'AAQ', 'country_code': 'RU', 'name_translations': {'en': 'Anapa Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 44.9, 'lon': 37.316666},
     'name': 'Витязево', 'code': 'AAQ', 'iata_type': 'airport', 'city_name': 'Анапа'},
    {'city_code': 'ERG', 'country_code': 'RU', 'name_translations': {'en': 'Erbogachyon'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 61.27361, 'lon': 108.02139}, 'name': 'Ербогачён', 'code': 'ЕГЧ',
     'iata_type': 'airport', 'city_name': 'Ербогачён'},
    {'city_code': 'ERG', 'country_code': 'RU', 'name_translations': {'en': 'Erbogachen Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 61.275, 'lon': 108.03},
     'name': 'Ербогачён', 'code': 'ERG', 'iata_type': 'airport', 'city_name': 'Ербогачён'},
    {'city_code': 'OVS', 'country_code': 'RU', 'name_translations': {'en': 'Sovetsky Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 61.33209, 'lon': 63.601887},
     'name': 'Советский', 'code': 'OVS', 'iata_type': 'airport', 'city_name': 'Советский'},
    {'city_code': 'VUS', 'country_code': 'RU', 'name_translations': {'en': 'Velikij Ustyug Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 60.766666, 'lon': 46.316666},
     'name': 'Великий Устюг', 'code': 'VUS', 'iata_type': 'airport', 'city_name': 'Великий Устюг'},
    {'city_code': 'NJC', 'country_code': 'RU', 'name_translations': {'en': 'Nizhnevartovsk Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 60.9476, 'lon': 76.49145},
     'name': 'Нижневартовск', 'code': 'NJC', 'iata_type': 'airport', 'city_name': 'Нижневартовск'},
    {'city_code': 'НЖГ', 'country_code': 'RU', 'name_translations': {'en': 'Nizhneangarsk'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 55.80111, 'lon': 109.59389},
     'name': 'Нижнеангарск', 'code': 'НЖГ', 'iata_type': 'airport', 'city_name': 'Нижнеангарск'},
    {'city_code': 'UKG', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Kuiga'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 70.00139, 'lon': 135.54971}, 'name': 'Усть-Куйга', 'code': 'UKG',
     'iata_type': 'airport', 'city_name': 'Усть-Куйга'},
    {'city_code': 'OGZ', 'country_code': 'RU', 'name_translations': {'en': 'Vladikavkaz Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 43.2, 'lon': 44.6}, 'name': 'Беслан',
     'code': 'OGZ', 'iata_type': 'airport', 'city_name': 'Владикавказ'},
    {'city_code': 'IKS', 'country_code': 'RU', 'name_translations': {'en': 'Tiksi Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 71.7, 'lon': 128.9}, 'name': 'Тикси',
     'code': 'IKS', 'iata_type': 'airport', 'city_name': 'Тикси'},
    {'city_code': 'RTW', 'country_code': 'RU', 'name_translations': {'en': 'Saratov Gagarin Airport'},
     'time_zone': 'Europe/Saratov', 'flightable': 'true', 'coordinates': {'lat': 51.716667, 'lon': 46.166668},
     'name': 'Гагарин', 'code': 'GSV', 'iata_type': 'airport', 'city_name': 'Саратов'},
    {'city_code': 'SCW', 'country_code': 'RU', 'name_translations': {'en': 'Syktyvkar Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 61.666668, 'lon': 50.766666},
     'name': 'Сыктывкар', 'code': 'SCW', 'iata_type': 'airport', 'city_name': 'Сыктывкар'},
    {'city_code': 'EGO', 'country_code': 'RU', 'name_translations': {'en': 'Belgorod Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 50.63333, 'lon': 36.65},
     'name': 'Белгород', 'code': 'EGO', 'iata_type': 'airport', 'city_name': 'Белгород'},
    {'city_code': 'SEK', 'country_code': 'RU', 'name_translations': {'en': 'Srednekolymsk Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 67.47972, 'lon': 153.735},
     'name': 'Среднеколымск', 'code': 'SEK', 'iata_type': 'airport', 'city_name': 'Среднеколымск'},
    {'city_code': 'HMA', 'country_code': 'RU', 'name_translations': {'en': 'Khanty-Mansiysk Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 61.02613, 'lon': 69.09714},
     'name': 'Ханты-Мансийск', 'code': 'HMA', 'iata_type': 'airport', 'city_name': 'Ханты-Мансийск'},
    {'city_code': 'BVJ', 'country_code': 'RU', 'name_translations': {'en': 'Bovanenkovo'}, 'time_zone': 'Asia/Dushanbe',
     'flightable': 'true', 'coordinates': {'lat': 70.31528, 'lon': 68.33361}, 'name': 'Бованенково', 'code': 'BVJ',
     'iata_type': 'airport', 'city_name': 'Бованенково'},
    {'city_code': 'NAL', 'country_code': 'RU', 'name_translations': {'en': 'Nalchik Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 43.533333, 'lon': 43.7},
     'name': 'Нальчик', 'code': 'NAL', 'iata_type': 'airport', 'city_name': 'Нальчик'},
    {'city_code': 'ZKP', 'country_code': 'RU', 'name_translations': {'en': 'Zyryanka Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 65.738335, 'lon': 150.70778},
     'name': 'Зырянка', 'code': 'ZKP', 'iata_type': 'airport', 'city_name': 'Зырянка'},
    {'city_code': 'VHV', 'country_code': 'RU', 'name_translations': {'en': 'Verhnevilyuisk'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 63.45667, 'lon': 120.26444},
     'name': 'Верхневилюйск', 'code': 'VHV', 'iata_type': 'airport', 'city_name': 'Верхневилюйск'},
    {'city_code': 'МЗН', 'country_code': 'RU', 'name_translations': {'en': 'Mezen'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 65.878334, 'lon': 44.216946}, 'name': 'Мезень', 'code': 'МЗН',
     'iata_type': 'airport', 'city_name': 'Мезень'},
    {'city_code': 'ROV', 'country_code': 'RU', 'name_translations': {'en': 'Platov International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 47.49417, 'lon': 39.92472},
     'name': 'Ростов-на-Дону (Платов)', 'code': 'ROV', 'iata_type': 'airport', 'city_name': 'Ростов-на-Дону'},
    {'city_code': 'ЧГД', 'country_code': 'RU', 'name_translations': {'en': 'Chegdomyn'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 51.13778, 'lon': 132.93611},
     'name': 'Чегдомын', 'code': 'ЧГД', 'iata_type': 'airport', 'city_name': 'Чегдомын'},
    {'city_code': 'УХЙ', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Khayryuzovo'},
     'time_zone': 'Asia/Kamchatka', 'flightable': 'true', 'coordinates': {'lat': 57.099167, 'lon': 156.73584},
     'name': 'Усть-Хайрюзово', 'code': 'УХЙ', 'iata_type': 'airport', 'city_name': 'Усть-Хайрюзово'},
    {'city_code': 'BQS', 'country_code': 'RU', 'name_translations': {'en': 'Blagoveschensk Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 50.416668, 'lon': 127.4},
     'name': 'Игнатьево', 'code': 'BQS', 'iata_type': 'airport', 'city_name': 'Благовещенск'},
    {'city_code': 'IJK', 'country_code': 'RU', 'name_translations': {'en': 'Izhevsk Airport'},
     'time_zone': 'Europe/Samara', 'flightable': 'true', 'coordinates': {'lat': 56.833332, 'lon': 53.466667},
     'name': 'Ижевск', 'code': 'IJK', 'iata_type': 'airport', 'city_name': 'Ижевск'},
    {'city_code': 'ШУШ', 'country_code': 'RU', 'name_translations': {'en': 'Shushenskoe'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 53.385555, 'lon': 92.04472},
     'name': 'Шушенское', 'code': 'ШУШ', 'iata_type': 'airport', 'city_name': 'Шушенское'},
    {'city_code': 'TOX', 'country_code': 'RU', 'name_translations': {'en': 'Tobolsk (Remezov)'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 58.050858, 'lon': 68.32763},
     'name': 'Тобольск (Ремезов)', 'code': 'RMZ', 'iata_type': 'airport', 'city_name': 'Тобольск'},
    {'city_code': 'BGN', 'country_code': 'RU', 'name_translations': {'en': 'Belaya Gora Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 68.538055, 'lon': 146.18584},
     'name': 'Белая Гора', 'code': 'BGN', 'iata_type': 'airport', 'city_name': 'Белая Гора'},
    {'city_code': 'NYR', 'country_code': 'RU', 'name_translations': {'en': 'Nyurba Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 63.297222, 'lon': 118.34695},
     'name': 'Нюрба', 'code': 'NYR', 'iata_type': 'airport', 'city_name': 'Нюрба'},
    {'city_code': 'URS', 'country_code': 'RU', 'name_translations': {'en': 'Kursk Vostochny Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 51.75, 'lon': 36.266666},
     'name': 'Восточный', 'code': 'URS', 'iata_type': 'airport', 'city_name': 'Курск'},
    {'city_code': 'NLI', 'country_code': 'RU', 'name_translations': {'en': 'Nikolaevsk-na-Amure'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 53.15278, 'lon': 140.65028},
     'name': 'Николаевск-на-Амуре', 'code': 'NLI', 'iata_type': 'airport', 'city_name': 'Николаевск-на-Амуре'},
    {'city_code': 'TJM', 'country_code': 'RU', 'name_translations': {'en': 'Roshchino International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 57.181828, 'lon': 65.35024},
     'name': 'Рощино', 'code': 'TJM', 'iata_type': 'airport', 'city_name': 'Тюмень'},
    {'city_code': 'TGP', 'country_code': 'RU', 'name_translations': {'en': 'Podkamennaya Tunguska Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 61.59, 'lon': 89.97945},
     'name': 'Подкаменная Тунгуска', 'code': 'TGP', 'iata_type': 'airport', 'city_name': 'Бор'},
    {'city_code': 'ASF', 'country_code': 'RU', 'name_translations': {'en': 'Astrakhan Airport'},
     'time_zone': 'Europe/Samara', 'flightable': 'true', 'coordinates': {'lat': 46.2877, 'lon': 47.999977},
     'name': 'Нариманово', 'code': 'ASF', 'iata_type': 'airport', 'city_name': 'Астрахань'},
    {'city_code': 'ZIX', 'country_code': 'RU', 'name_translations': {'en': 'Zhigansk Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 66.79667, 'lon': 123.36139},
     'name': 'Жиганск', 'code': 'ZIX', 'iata_type': 'airport', 'city_name': 'Жиганск'},
    {'city_code': 'ДЛЧ', 'country_code': 'RU', 'name_translations': {'en': 'Dalnerechensk'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 45.876667, 'lon': 133.735},
     'name': 'Дальнереченск', 'code': 'ДЛЧ', 'iata_type': 'airport', 'city_name': 'Дальнереченск'},
    {'city_code': 'ZZO', 'country_code': 'RU', 'name_translations': {'en': 'Zonalnoye'}, 'time_zone': 'Asia/Sakhalin',
     'flightable': 'true', 'coordinates': {'lat': 50.666668, 'lon': 142.75}, 'name': 'null', 'code': 'ZZO',
     'iata_type': 'airport', 'city_name': 'Зональное'},
    {'city_code': 'GDX', 'country_code': 'RU', 'name_translations': {'en': 'Magadan Airport'},
     'time_zone': 'Asia/Magadan', 'flightable': 'true', 'coordinates': {'lat': 59.916668, 'lon': 150.71666},
     'name': 'Сокол', 'code': 'GDX', 'iata_type': 'airport', 'city_name': 'Магадан'},
    {'city_code': 'ЯМБ', 'country_code': 'RU', 'name_translations': {'en': 'Yamburg'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 67.988335, 'lon': 75.09695},
     'name': 'Ямбург', 'code': 'ЯМБ', 'iata_type': 'airport', 'city_name': 'Ямбург'},
    {'city_code': 'OHO', 'country_code': 'RU', 'name_translations': {'en': 'Okhotsk'}, 'time_zone': 'Asia/Vladivostok',
     'flightable': 'true', 'coordinates': {'lat': 59.416668, 'lon': 143.05}, 'name': 'Охотск', 'code': 'OHO',
     'iata_type': 'airport', 'city_name': 'Охотск'},
    {'city_code': 'THX', 'country_code': 'RU', 'name_translations': {'en': 'Turukhansk Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 65.79722, 'lon': 87.93528},
     'name': 'Туруханск', 'code': 'THX', 'iata_type': 'airport', 'city_name': 'Туруханск'},
    {'city_code': 'OSW', 'country_code': 'RU', 'name_translations': {'en': 'Orsk Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 51.2, 'lon': 58.566666},
     'name': 'Орск', 'code': 'OSW', 'iata_type': 'airport', 'city_name': 'Орск'},
    {'city_code': 'TLY', 'country_code': 'RU', 'name_translations': {'en': 'Plastun Airport'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 44.81465, 'lon': 136.28928},
     'name': 'Пластун', 'code': 'TLY', 'iata_type': 'airport', 'city_name': 'Пластун'},
    {'city_code': 'УКО', 'country_code': 'RU', 'name_translations': {'en': "Ust'-Koksa"},
     'time_zone': 'Asia/Novosibirsk', 'flightable': 'true', 'coordinates': {'lat': 50.263557, 'lon': 85.710144},
     'name': 'Усть-Кокса', 'code': 'УКО', 'iata_type': 'airport', 'city_name': 'Усть-Кокса'},
    {'city_code': 'BZK', 'country_code': 'RU', 'name_translations': {'en': 'Bryansk International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 53.266666, 'lon': 34.333332},
     'name': 'Брянск', 'code': 'BZK', 'iata_type': 'airport', 'city_name': 'Брянск'},
    {'city_code': 'LPK', 'country_code': 'RU', 'name_translations': {'en': 'Lipetsk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 52.61667, 'lon': 39.6},
     'name': 'Липецк', 'code': 'LPK', 'iata_type': 'airport', 'city_name': 'Липецк'},
    {'city_code': 'САГ', 'country_code': 'RU', 'name_translations': {'en': 'Sangar'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 63.95889, 'lon': 127.42111}, 'name': 'Сангар', 'code': 'САГ',
     'iata_type': 'airport', 'city_name': 'Сангар'},
    {'city_code': 'TGK', 'country_code': 'RU', 'name_translations': {'en': 'Taganrog'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 47.243378, 'lon': 38.864017}, 'name': 'Южный', 'code': 'TGK',
     'iata_type': 'airport', 'city_name': 'Таганрог'},
    {'city_code': 'KGP', 'country_code': 'RU', 'name_translations': {'en': 'Kogalym International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 62.19583, 'lon': 74.53361},
     'name': 'Когалым', 'code': 'KGP', 'iata_type': 'airport', 'city_name': 'Когалым'},
    {'city_code': 'GDZ', 'country_code': 'RU', 'name_translations': {'en': 'Gelendzik Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 44.566666, 'lon': 38.016666},
     'name': 'Геленджик', 'code': 'GDZ', 'iata_type': 'airport', 'city_name': 'Геленджик'},
    {'city_code': 'NSK', 'country_code': 'RU', 'name_translations': {'en': "Noril'sk Airport"},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 69.32312, 'lon': 87.339806},
     'name': 'Норильск', 'code': 'NSK', 'iata_type': 'airport', 'city_name': 'Норильск'},
    {'city_code': 'ЯРЦ', 'country_code': 'RU', 'name_translations': {'en': 'Yartsevo'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 60.254444, 'lon': 90.19583}, 'name': 'Ярцево', 'code': 'ЯРЦ',
     'iata_type': 'airport', 'city_name': 'Ярцево'},
    {'city_code': 'KZN', 'country_code': 'RU', 'name_translations': {'en': 'Kazan International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.60844, 'lon': 49.29824},
     'name': 'Казань', 'code': 'KZN', 'iata_type': 'airport', 'city_name': 'Казань'},
    {'city_code': 'КНК', 'country_code': 'RU', 'name_translations': {'en': 'Krasnokamensk'}, 'time_zone': 'Asia/Chita',
     'flightable': 'true', 'coordinates': {'lat': 50.05, 'lon': 118.11667}, 'name': 'Краснокаменск', 'code': 'КНК',
     'iata_type': 'airport', 'city_name': 'Краснокаменск'},
    {'city_code': 'UMS', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Maya'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 60.35806, 'lon': 134.43777}, 'name': 'Усть-Мая', 'code': 'UMS',
     'iata_type': 'airport', 'city_name': 'Усть-Мая'},
    {'city_code': 'NER', 'country_code': 'RU', 'name_translations': {'en': 'Neryungri Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 56.65, 'lon': 124.6}, 'name': 'Чульман',
     'code': 'NER', 'iata_type': 'airport', 'city_name': 'Нерюнгри'},
    {'city_code': 'MQF', 'country_code': 'RU', 'name_translations': {'en': 'Magnitogorsk Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 53.45, 'lon': 59.066666},
     'name': 'Магнитогорск', 'code': 'MQF', 'iata_type': 'airport', 'city_name': 'Магнитогорск'},
    {'city_code': 'ПАЧ', 'country_code': 'RU', 'name_translations': {'en': 'Pakhachi'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 60.55611, 'lon': 169.10472}, 'name': 'Пахачи', 'code': 'ПАЧ',
     'iata_type': 'airport', 'city_name': 'Пахачи'},
    {'city_code': 'DKS', 'country_code': 'RU', 'name_translations': {'en': 'Dikson'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 73.51667, 'lon': 80.36667}, 'name': 'Диксон', 'code': 'DKS',
     'iata_type': 'airport', 'city_name': 'Диксон'},
    {'city_code': 'SVX', 'country_code': 'RU', 'name_translations': {'en': 'Koltsovo International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 56.750336, 'lon': 60.804314},
     'name': 'Кольцово', 'code': 'SVX', 'iata_type': 'airport', 'city_name': 'Екатеринбург'},
    {'city_code': 'MRV', 'country_code': 'RU', 'name_translations': {'en': 'Mineralnye Vody Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 44.218105, 'lon': 43.085815},
     'name': 'Минеральные Воды', 'code': 'MRV', 'iata_type': 'airport', 'city_name': 'Минеральные Воды'},
    {'city_code': 'VGD', 'country_code': 'RU', 'name_translations': {'en': 'Vologda Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 59.283333, 'lon': 39.95},
     'name': 'Вологда', 'code': 'VGD', 'iata_type': 'airport', 'city_name': 'Вологда'},
    {'city_code': 'MOW', 'country_code': 'RU', 'name_translations': {'en': 'MOW'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.966324, 'lon': 37.416573},
     'name': 'все аэропорты', 'code': 'MOW', 'iata_type': 'airport', 'city_name': 'Москва'},
    {'city_code': 'MOW', 'country_code': 'RU', 'name_translations': {'en': 'Sheremetyevo International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.966324, 'lon': 37.416573},
     'name': 'Шереметьево', 'code': 'SVO', 'iata_type': 'airport', 'city_name': 'Москва'},
    {'city_code': 'MOW', 'country_code': 'RU', 'name_translations': {'en': 'Vnukovo Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.60315, 'lon': 37.2921},
     'name': 'Внуково', 'code': 'VKO', 'iata_type': 'airport', 'city_name': 'Москва'},
    {'city_code': 'MOW', 'country_code': 'RU', 'name_translations': {'en': 'Zhukovsky International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.569016, 'lon': 38.141964},
     'name': 'Жуковский', 'code': 'ZIA', 'iata_type': 'airport', 'city_name': 'Москва'},
    {'city_code': 'MOW', 'country_code': 'RU', 'name_translations': {'en': 'Moscow Domodedovo Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.414566, 'lon': 37.899494},
     'name': 'Домодедово', 'code': 'DME', 'iata_type': 'airport', 'city_name': 'Москва'},
    {'city_code': 'IAA', 'country_code': 'RU', 'name_translations': {'en': 'Igarka Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 67.433334, 'lon': 86.63333},
     'name': 'Игарка', 'code': 'IAA', 'iata_type': 'airport', 'city_name': 'Игарка'},
    {'city_code': 'БКТ', 'country_code': 'RU', 'name_translations': {'en': 'Bajkit'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 61.676666, 'lon': 96.35333}, 'name': 'Байкит', 'code': 'БКТ',
     'iata_type': 'airport', 'city_name': 'Байкит'},
    {'city_code': 'KVK', 'country_code': 'RU', 'name_translations': {'en': 'Kirovsk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 67.583336, 'lon': 33.583332},
     'name': 'Хибины', 'code': 'KVK', 'iata_type': 'airport', 'city_name': 'Кировск (Апатиты)'},
    {'city_code': 'SKX', 'country_code': 'RU', 'name_translations': {'en': 'Saransk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 54.166668, 'lon': 45.166668},
     'name': 'Саранск', 'code': 'SKX', 'iata_type': 'airport', 'city_name': 'Саранск'},
    {'city_code': 'MMK', 'country_code': 'RU', 'name_translations': {'en': 'Murmansk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 68.785095, 'lon': 32.759155},
     'name': 'Мурманск', 'code': 'MMK', 'iata_type': 'airport', 'city_name': 'Мурманск'},
    {'city_code': 'КГЬ', 'country_code': 'RU', 'name_translations': {'en': 'Kuskurgul'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 58.091667, 'lon': 66.605},
     'name': 'Кускургуль', 'code': 'КГЬ', 'iata_type': 'airport', 'city_name': 'Кускургуль'},
    {'city_code': 'TQL', 'country_code': 'RU', 'name_translations': {'en': 'Tarko-Sale'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 64.92134, 'lon': 77.797356},
     'name': 'null', 'code': 'TQL', 'iata_type': 'airport', 'city_name': 'Тарко-Сале'},
    {'city_code': 'АЯН', 'country_code': 'RU', 'name_translations': {'en': 'Ajan'}, 'time_zone': 'Asia/Vladivostok',
     'flightable': 'true', 'coordinates': {'lat': 56.43028, 'lon': 138.04973}, 'name': 'Аян', 'code': 'АЯН',
     'iata_type': 'airport', 'city_name': 'Аян'},
    {'city_code': 'OHH', 'country_code': 'RU', 'name_translations': {'en': 'Novostroyka Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 53.516666, 'lon': 142.88333},
     'name': 'Оха', 'code': 'OHH', 'iata_type': 'airport', 'city_name': 'Оха'},
    {'city_code': 'KKQ', 'country_code': 'RU', 'name_translations': {'en': 'Krasnoselkup'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 65.70796, 'lon': 82.456055},
     'name': 'Красноселькуп', 'code': 'KKQ', 'iata_type': 'airport', 'city_name': 'Красноселькуп'},
    {'city_code': 'USK', 'country_code': 'RU', 'name_translations': {'en': 'Usinsk Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 65.95, 'lon': 57.4}, 'name': 'Усинск',
     'code': 'USK', 'iata_type': 'airport', 'city_name': 'Усинск'},
    {'city_code': 'TLK', 'country_code': 'RU', 'name_translations': {'en': 'Talakan'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 59.8692, 'lon': 111.04371}, 'name': 'Талакан', 'code': 'TLK',
     'iata_type': 'airport', 'city_name': 'Талакан'},
    {'city_code': 'БОЧ', 'country_code': 'RU', 'name_translations': {'en': 'Boguchany'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 58.380554, 'lon': 97.47278},
     'name': 'Богучаны', 'code': 'БОЧ', 'iata_type': 'airport', 'city_name': 'Богучаны'},
    {'city_code': 'KMW', 'country_code': 'RU', 'name_translations': {'en': 'Sokerkino'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 57.75, 'lon': 40.933334}, 'name': 'Кострома', 'code': 'KMW',
     'iata_type': 'airport', 'city_name': 'Кострома'},
    {'city_code': 'CYX', 'country_code': 'RU', 'name_translations': {'en': 'Cherskiy Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 68.75, 'lon': 161.35},
     'name': 'Черский', 'code': 'CYX', 'iata_type': 'airport', 'city_name': 'Черский'},
    {'city_code': 'ITU', 'country_code': 'RU', 'name_translations': {'en': 'Iturup'}, 'time_zone': 'Asia/Srednekolymsk',
     'flightable': 'true', 'coordinates': {'lat': 45.25611, 'lon': 147.95583}, 'name': 'Ясный', 'code': 'ITU',
     'iata_type': 'airport', 'city_name': 'Итуруп'},
    {'city_code': 'МТГ', 'country_code': 'RU', 'name_translations': {'en': 'Motygino'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 58.180832, 'lon': 94.74472}, 'name': 'Мотыгино', 'code': 'МТГ',
     'iata_type': 'airport', 'city_name': 'Мотыгино'},
    {'city_code': 'ONK', 'country_code': 'RU', 'name_translations': {'en': 'Olenyok Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 68.51556, 'lon': 112.479164},
     'name': 'Оленёк', 'code': 'ONK', 'iata_type': 'airport', 'city_name': 'Оленёк'},
    {'city_code': 'ONK', 'country_code': 'RU', 'name_translations': {'en': 'Olenyok'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 68.51528, 'lon': 112.47694}, 'name': 'Оленёк', 'code': 'ОЛН',
     'iata_type': 'airport', 'city_name': 'Оленёк'},
    {'city_code': 'МКО', 'country_code': 'RU', 'name_translations': {'en': 'Markovo'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 64.66472, 'lon': 170.4136}, 'name': 'Марково', 'code': 'МКО',
     'iata_type': 'airport', 'city_name': 'Марково'},
    {'city_code': 'SGC', 'country_code': 'RU', 'name_translations': {'en': 'Surgut Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 61.339916, 'lon': 73.40953},
     'name': 'Сургут', 'code': 'SGC', 'iata_type': 'airport', 'city_name': 'Сургут'},
    {'city_code': 'LED', 'country_code': 'RU', 'name_translations': {'en': 'Pulkovo Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 59.806084, 'lon': 30.3083},
     'name': 'Пулково', 'code': 'LED', 'iata_type': 'airport', 'city_name': 'Санкт-Петербург'},
    {'city_code': 'УКЧ', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Kamchatsk'},
     'time_zone': 'Asia/Kamchatka', 'flightable': 'true', 'coordinates': {'lat': 56.237778, 'lon': 162.68556},
     'name': 'Усть-Камчатск', 'code': 'УКЧ', 'iata_type': 'airport', 'city_name': 'Усть-Камчатск'},
    {'city_code': 'CKH', 'country_code': 'RU', 'name_translations': {'en': 'Chokurdah Airport'},
     'time_zone': 'Asia/Srednekolymsk', 'flightable': 'true', 'coordinates': {'lat': 70.63333, 'lon': 147.88333},
     'name': 'Чокурдах', 'code': 'CKH', 'iata_type': 'airport', 'city_name': 'Чокурдах'},
    {'city_code': 'KHV', 'country_code': 'RU', 'name_translations': {'en': 'Khabarovsk Airport'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 48.524563, 'lon': 135.16861},
     'name': 'Хабаровск', 'code': 'KHV', 'iata_type': 'airport', 'city_name': 'Хабаровск'},
    {'city_code': 'СВЕ', 'country_code': 'RU', 'name_translations': {'en': 'Severo-Evensk'},
     'time_zone': 'Asia/Magadan', 'flightable': 'true', 'coordinates': {'lat': 61.92139, 'lon': 159.22972},
     'name': 'Северо-Эвенск', 'code': 'СВЕ', 'iata_type': 'airport', 'city_name': 'Северо-Эвенск'},
    {'city_code': 'KVR', 'country_code': 'RU', 'name_translations': {'en': 'Kavalerovo'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 44.266865, 'lon': 135.0357},
     'name': 'Кавалерово', 'code': 'KVR', 'iata_type': 'airport', 'city_name': 'Кавалерово'},
    {'city_code': 'ULK', 'country_code': 'RU', 'name_translations': {'en': 'Lensk Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 60.72248, 'lon': 114.83152},
     'name': 'Ленск', 'code': 'ULK', 'iata_type': 'airport', 'city_name': 'Ленск'},
    {'city_code': 'ODO', 'country_code': 'RU', 'name_translations': {'en': 'Bodaybo Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 57.86639, 'lon': 114.2425},
     'name': 'Бодайбо', 'code': 'ODO', 'iata_type': 'airport', 'city_name': 'Бодайбо'},
    {'city_code': 'PEZ', 'country_code': 'RU', 'name_translations': {'en': 'Penza Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 53.11852, 'lon': 45.02305},
     'name': 'Пенза', 'code': 'PEZ', 'iata_type': 'airport', 'city_name': 'Пенза'},
    {'city_code': 'NBC', 'country_code': 'RU', 'name_translations': {'en': 'Begishevo Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 55.564125, 'lon': 52.10341},
     'name': 'Бегишево', 'code': 'NBC', 'iata_type': 'airport', 'city_name': 'Набережные Челны (Нижнекамск)'},
    {'city_code': 'КЗИ', 'country_code': 'RU', 'name_translations': {'en': 'Kodinsk'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 58.48, 'lon': 99.095}, 'name': 'Кодинск', 'code': 'КЗИ',
     'iata_type': 'airport', 'city_name': 'Кодинск'},
    {'city_code': 'ЧМИ', 'country_code': 'RU', 'name_translations': {'en': 'Chumikan'}, 'time_zone': 'Asia/Vladivostok',
     'flightable': 'true', 'coordinates': {'lat': 54.695, 'lon': 135.28334}, 'name': 'Чумикан', 'code': 'ЧМИ',
     'iata_type': 'airport', 'city_name': 'Чумикан'},
    {'city_code': 'RGK', 'country_code': 'RU', 'name_translations': {'en': 'Gorno-Altaysk Airport'},
     'time_zone': 'Asia/Novokuznetsk', 'flightable': 'true', 'coordinates': {'lat': 51.969166, 'lon': 85.83639},
     'name': 'Горно-Алтайск', 'code': 'RGK', 'iata_type': 'airport', 'city_name': 'Горно-Алтайск'},
    {'city_code': 'СЕН', 'country_code': 'RU', 'name_translations': {'en': 'Severo-Eniseyskij'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 60.373333, 'lon': 93.01667},
     'name': 'Северо-Енисейский', 'code': 'СЕН', 'iata_type': 'airport', 'city_name': 'Северо-Енисейский'},
    {'city_code': 'UUA', 'country_code': 'RU', 'name_translations': {'en': 'Bugulma Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 54.61667, 'lon': 52.816666},
     'name': 'Бугульма', 'code': 'UUA', 'iata_type': 'airport', 'city_name': 'Бугульма'},
    {'city_code': 'KXK', 'country_code': 'RU', 'name_translations': {'en': 'Khurba Airport'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 50.4, 'lon': 136.95},
     'name': 'Комсомольск-на-Амуре', 'code': 'KXK', 'iata_type': 'airport', 'city_name': 'Комсомольск-на-Амуре'},
    {'city_code': 'DEE', 'country_code': 'RU', 'name_translations': {'en': 'Mendeleyevo Airport'},
     'time_zone': 'Asia/Sakhalin', 'flightable': 'true', 'coordinates': {'lat': 43.9584, 'lon': 145.683},
     'name': 'Менделеево', 'code': 'DEE', 'iata_type': 'airport', 'city_name': 'Южно-Курильск'},
    {'city_code': 'KSZ', 'country_code': 'RU', 'name_translations': {'en': 'Kotlas Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 61.233334, 'lon': 46.7},
     'name': 'Котлас', 'code': 'KSZ', 'iata_type': 'airport', 'city_name': 'Котлас'},
    {'city_code': 'INA', 'country_code': 'RU', 'name_translations': {'en': 'Inta Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 66.066666, 'lon': 60.1}, 'name': 'Инта',
     'code': 'INA', 'iata_type': 'airport', 'city_name': 'Инта'},
    {'city_code': 'SUY', 'country_code': 'RU', 'name_translations': {'en': 'Suntar'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 62.184723, 'lon': 117.63611}, 'name': 'Сунтар', 'code': 'SUY',
     'iata_type': 'airport', 'city_name': 'Сунтар'},
    {'city_code': 'SLY', 'country_code': 'RU', 'name_translations': {'en': 'Salekhard Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 66.583336, 'lon': 66.6},
     'name': 'Салехард', 'code': 'SLY', 'iata_type': 'airport', 'city_name': 'Салехард'},
    {'city_code': 'TBW', 'country_code': 'RU', 'name_translations': {'en': 'Tambov Donskoye Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 52.716667, 'lon': 41.433334},
     'name': 'Донское', 'code': 'TBW', 'iata_type': 'airport', 'city_name': 'Тамбов'},
    {'city_code': 'UIK', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Ilimsk'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 58.13333, 'lon': 102.55}, 'name': 'Усть-Илимск', 'code': 'UIK',
     'iata_type': 'airport', 'city_name': 'Усть-Илимск'},
    {'city_code': 'НИК', 'country_code': 'RU', 'name_translations': {'en': 'Nikolskoe'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 55.1775, 'lon': 166.045}, 'name': 'Никольское', 'code': 'НИК',
     'iata_type': 'airport', 'city_name': 'Никольское'},
    {'city_code': 'IAR', 'country_code': 'RU', 'name_translations': {'en': 'Tunoshna Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 57.61667, 'lon': 39.88333},
     'name': 'Ярославль', 'code': 'IAR', 'iata_type': 'airport', 'city_name': 'Ярославль'},
    {'city_code': 'PWE', 'country_code': 'RU', 'name_translations': {'en': 'Pevek Airport'}, 'time_zone': 'Asia/Anadyr',
     'flightable': 'true', 'coordinates': {'lat': 69.78333, 'lon': 170.6}, 'name': 'Певек', 'code': 'PWE',
     'iata_type': 'airport', 'city_name': 'Певек'},
    {'city_code': 'DYR', 'country_code': 'RU', 'name_translations': {'en': 'Anadyr Airport'},
     'time_zone': 'Asia/Anadyr', 'flightable': 'true', 'coordinates': {'lat': 64.73333, 'lon': 177.75},
     'name': 'Угольный', 'code': 'DYR', 'iata_type': 'airport', 'city_name': 'Анадырь'},
    {'city_code': 'NOJ', 'country_code': 'RU', 'name_translations': {'en': 'Nojabrxsk Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 63.17673, 'lon': 75.29459},
     'name': 'Ноябрьск', 'code': 'NOJ', 'iata_type': 'airport', 'city_name': 'Ноябрьск'},
    {'city_code': 'СЕГ', 'country_code': 'RU', 'name_translations': {'en': 'Svetlogorsk'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 66.83833, 'lon': 88.40667},
     'name': 'Светлогорск', 'code': 'СЕГ', 'iata_type': 'airport', 'city_name': 'Светлогорск'},
    {'city_code': 'SYS', 'country_code': 'RU', 'name_translations': {'en': 'Saskylakh Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 71.92606, 'lon': 114.08317},
     'name': 'Саскылах', 'code': 'SYS', 'iata_type': 'airport', 'city_name': 'Саскылах'},
    {'city_code': 'SYS', 'country_code': 'RU', 'name_translations': {'en': 'Saskylakh'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 71.92833, 'lon': 114.08}, 'name': 'Саскылах', 'code': 'СЫХ',
     'iata_type': 'airport', 'city_name': 'Саскылах'},
    {'city_code': 'СМЧ', 'country_code': 'RU', 'name_translations': {'en': 'Seymchan'}, 'time_zone': 'Asia/Magadan',
     'flightable': 'true', 'coordinates': {'lat': 62.916668, 'lon': 152.41667}, 'name': 'Сеймчан', 'code': 'СМЧ',
     'iata_type': 'airport', 'city_name': 'Сеймчан'},
    {'city_code': 'ВЛМ', 'country_code': 'RU', 'name_translations': {'en': 'Vladimir'}, 'time_zone': 'Europe/Moscow',
     'flightable': 'true', 'coordinates': {'lat': 56.126667, 'lon': 40.316666}, 'name': 'Владимир', 'code': 'ВЛМ',
     'iata_type': 'airport', 'city_name': 'Владимир'},
    {'city_code': 'KJA', 'country_code': 'RU', 'name_translations': {'en': 'Krasnoyarsk International Airport'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 56.18113, 'lon': 92.48286},
     'name': 'Международный аэропорт Красноярск', 'code': 'KJA', 'iata_type': 'airport', 'city_name': 'Красноярск'},
    {'city_code': 'KJA', 'country_code': 'RU', 'name_translations': {'en': 'Cheremshanka'},
     'time_zone': 'Asia/Krasnoyarsk', 'flightable': 'true', 'coordinates': {'lat': 56.176666, 'lon': 92.543335},
     'name': 'Черемшанка', 'code': 'КЯС', 'iata_type': 'airport', 'city_name': 'Красноярск'},
    {'city_code': 'ЛАЙ', 'country_code': 'RU', 'name_translations': {'en': 'Laitamak'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 58.411945, 'lon': 67.458336},
     'name': 'Лайтамак', 'code': 'ЛАЙ', 'iata_type': 'airport', 'city_name': 'Лайтамак'},
    {'city_code': 'LDG', 'country_code': 'RU', 'name_translations': {'en': 'Leshukonskoye'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 64.9, 'lon': 45.75},
     'name': 'Лешуконское', 'code': 'LDG', 'iata_type': 'airport', 'city_name': 'Лешуконское'},
    {'city_code': 'USR', 'country_code': 'RU', 'name_translations': {'en': 'Ust-Nera Airport'},
     'time_zone': 'Asia/Ust-Nera', 'flightable': 'true', 'coordinates': {'lat': 64.549446, 'lon': 143.11084},
     'name': 'Усть-Нера', 'code': 'USR', 'iata_type': 'airport', 'city_name': 'Усть-Нера'},
    {'city_code': 'URJ', 'country_code': 'RU', 'name_translations': {'en': 'Uraj Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 60.11667, 'lon': 64.833336},
     'name': 'Урай', 'code': 'URJ', 'iata_type': 'airport', 'city_name': 'Урай'},
    {'city_code': 'SUK', 'country_code': 'RU', 'name_translations': {'en': 'Sakkyryr Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 67.79257, 'lon': 130.39194},
     'name': 'Саккырыр', 'code': 'SUK', 'iata_type': 'airport', 'city_name': 'Батагай-Алыта'},
    {'city_code': 'AER', 'country_code': 'RU', 'name_translations': {'en': 'Sochi International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 43.44884, 'lon': 39.941105},
     'name': 'Адлер', 'code': 'AER', 'iata_type': 'airport', 'city_name': 'Сочи'},
    {'city_code': 'BQG', 'country_code': 'RU', 'name_translations': {'en': 'Bogorodskoye'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 52.378334, 'lon': 140.44833},
     'name': 'Богородское', 'code': 'BQG', 'iata_type': 'airport', 'city_name': 'Богородское'},
    {'city_code': 'KCK', 'country_code': 'RU', 'name_translations': {'en': 'Kirensk Airport'},
     'time_zone': 'Asia/Irkutsk', 'flightable': 'true', 'coordinates': {'lat': 57.772778, 'lon': 108.06084},
     'name': 'Киренск', 'code': 'KCK', 'iata_type': 'airport', 'city_name': 'Киренск'},
    {'city_code': 'EZV', 'country_code': 'RU', 'name_translations': {'en': 'Berezovo'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 63.924583, 'lon': 65.04485},
     'name': 'Березово', 'code': 'EZV', 'iata_type': 'airport', 'city_name': 'Берёзово'},
    {'city_code': 'REN', 'country_code': 'RU', 'name_translations': {'en': 'Orenburg Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 51.79105, 'lon': 55.4567},
     'name': 'Оренбург', 'code': 'REN', 'iata_type': 'airport', 'city_name': 'Оренбург'},
    {'city_code': 'VVO', 'country_code': 'RU', 'name_translations': {'en': 'Vladivostok International Airport'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 43.378574, 'lon': 132.14075},
     'name': 'Кневичи', 'code': 'VVO', 'iata_type': 'airport', 'city_name': 'Владивосток'},
    {'city_code': 'DPT', 'country_code': 'RU', 'name_translations': {'en': 'Deputatsky'}, 'time_zone': 'Asia/Yakutsk',
     'flightable': 'true', 'coordinates': {'lat': 69.39167, 'lon': 139.89917}, 'name': 'Депутатский', 'code': 'DPT',
     'iata_type': 'airport', 'city_name': 'Депутатский'},
    {'city_code': 'MJZ', 'country_code': 'RU', 'name_translations': {'en': 'Mirnyj Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 62.533333, 'lon': 114.03333},
     'name': 'Мирный', 'code': 'MJZ', 'iata_type': 'airport', 'city_name': 'Мирный'},
    {'city_code': 'ТРЛ', 'country_code': 'RU', 'name_translations': {'en': 'Tura'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 64.27583, 'lon': 100.21639}, 'name': 'Тура', 'code': 'ТРЛ',
     'iata_type': 'airport', 'city_name': 'Тура'},
    {'city_code': 'ВАГ', 'country_code': 'RU', 'name_translations': {'en': 'Vagay'}, 'time_zone': 'Asia/Yekaterinburg',
     'flightable': 'true', 'coordinates': {'lat': 57.927223, 'lon': 69.00667}, 'name': 'Вагай', 'code': 'ВАГ',
     'iata_type': 'airport', 'city_name': 'Вагай'},
    {'city_code': 'ОСО', 'country_code': 'RU', 'name_translations': {'en': 'Ossora'}, 'time_zone': 'Asia/Kamchatka',
     'flightable': 'true', 'coordinates': {'lat': 59.22361, 'lon': 163.06639}, 'name': 'Оссора', 'code': 'ОСО',
     'iata_type': 'airport', 'city_name': 'Оссора'},
    {'city_code': 'ТАУ', 'country_code': 'RU', 'name_translations': {'en': 'Gornyj'}, 'time_zone': 'Asia/Krasnoyarsk',
     'flightable': 'true', 'coordinates': {'lat': 64.333336, 'lon': 100.433334}, 'name': 'Горный', 'code': 'ТАУ',
     'iata_type': 'airport', 'city_name': 'Тура'},
    {'city_code': 'ESL', 'country_code': 'RU', 'name_translations': {'en': 'Elista Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 46.36667, 'lon': 44.333332},
     'name': 'Элиста', 'code': 'ESL', 'iata_type': 'airport', 'city_name': 'Элиста'},
    {'city_code': 'CEK', 'country_code': 'RU', 'name_translations': {'en': 'Chelyabinsk International Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 55.297504, 'lon': 61.51235},
     'name': 'Баландино', 'code': 'CEK', 'iata_type': 'airport', 'city_name': 'Челябинск'},
    {'city_code': 'IGT', 'country_code': 'RU', 'name_translations': {'en': 'Magas Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 43.31778, 'lon': 45.001667},
     'name': 'Магас', 'code': 'IGT', 'iata_type': 'airport', 'city_name': 'Магас'},
    {'city_code': 'UCT', 'country_code': 'RU', 'name_translations': {'en': 'Ukhta Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 63.566666, 'lon': 53.8}, 'name': 'Ухта',
     'code': 'UCT', 'iata_type': 'airport', 'city_name': 'Ухта'},
    {'city_code': 'PKC', 'country_code': 'RU', 'name_translations': {'en': 'Petropavlovsk-Kamchatsky Airport'},
     'time_zone': 'Asia/Kamchatka', 'flightable': 'true', 'coordinates': {'lat': 53.016666, 'lon': 158.65},
     'name': 'Елизово', 'code': 'PKC', 'iata_type': 'airport', 'city_name': 'Петропавловск-Камчатский'},
    {'city_code': 'KEJ', 'country_code': 'RU', 'name_translations': {'en': 'Kemerovo Airport'},
     'time_zone': 'Asia/Novokuznetsk', 'flightable': 'true', 'coordinates': {'lat': 55.280567, 'lon': 86.11623},
     'name': 'Кемерово', 'code': 'KEJ', 'iata_type': 'airport', 'city_name': 'Кемерово'},
    {'city_code': 'GRV', 'country_code': 'RU', 'name_translations': {'en': 'Groznyy Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 43.333332, 'lon': 45.75},
     'name': 'Грозный', 'code': 'GRV', 'iata_type': 'airport', 'city_name': 'Грозный'},
    {'city_code': 'EKS', 'country_code': 'RU', 'name_translations': {'en': 'Shakhtyorsk Airport'},
     'time_zone': 'Asia/Sakhalin', 'flightable': 'true', 'coordinates': {'lat': 49.190735, 'lon': 142.0777},
     'name': 'Шахтёрск', 'code': 'EKS', 'iata_type': 'airport', 'city_name': 'Шахтёрск'},
    {'city_code': 'KVX', 'country_code': 'RU', 'name_translations': {'en': 'Kirov Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 58.5, 'lon': 49.35},
     'name': 'Победилово', 'code': 'KVX', 'iata_type': 'airport', 'city_name': 'Киров'},
    {'city_code': 'ХЖР', 'country_code': 'RU', 'name_translations': {'en': 'Khuzhir'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 53.216667, 'lon': 107.395}, 'name': 'Хужир', 'code': 'ХЖР',
     'iata_type': 'airport', 'city_name': 'Хужир'},
    {'city_code': 'RZH', 'country_code': 'RU', 'name_translations': {'en': 'Preobrazheniye'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 42.921112, 'lon': 133.90334},
     'name': 'Преображение', 'code': 'RZH', 'iata_type': 'airport', 'city_name': 'Преображение'},
    {'city_code': 'GVN', 'country_code': 'RU', 'name_translations': {'en': 'May-Gatka'},
     'time_zone': 'Asia/Vladivostok', 'flightable': 'true', 'coordinates': {'lat': 48.928535, 'lon': 140.01697},
     'name': 'Советская гавань', 'code': 'GVN', 'iata_type': 'airport', 'city_name': 'Советская Гавань'},
    {'city_code': 'OLZ', 'country_code': 'RU', 'name_translations': {'en': 'Olokminsk Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 60.399166, 'lon': 120.464165},
     'name': 'Олёкминск', 'code': 'OLZ', 'iata_type': 'airport', 'city_name': 'Олёкминск'},
    {'city_code': 'NYA', 'country_code': 'RU', 'name_translations': {'en': 'Nyagan Airport'},
     'time_zone': 'Asia/Yekaterinburg', 'flightable': 'true', 'coordinates': {'lat': 62.101074, 'lon': 65.60563},
     'name': 'Нягань', 'code': 'NYA', 'iata_type': 'airport', 'city_name': 'Нягань'},
    {'city_code': 'VKT', 'country_code': 'RU', 'name_translations': {'en': 'Vorkuta Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 67.48333, 'lon': 63.983334},
     'name': 'Воркута', 'code': 'VKT', 'iata_type': 'airport', 'city_name': 'Воркута'},
    {'city_code': 'SWT', 'country_code': 'RU', 'name_translations': {'en': 'Strezhevoy Airport'},
     'time_zone': 'Asia/Novosibirsk', 'flightable': 'true', 'coordinates': {'lat': 60.5, 'lon': 77},
     'name': 'Стрежевой', 'code': 'SWT', 'iata_type': 'airport', 'city_name': 'Стрежевой'},
    {'city_code': 'YKS', 'country_code': 'RU', 'name_translations': {'en': 'Yakutsk Airport'},
     'time_zone': 'Asia/Yakutsk', 'flightable': 'true', 'coordinates': {'lat': 62.085606, 'lon': 129.75006},
     'name': 'Якутск', 'code': 'YKS', 'iata_type': 'airport', 'city_name': 'Якутск'},
    {'city_code': 'KGD', 'country_code': 'RU', 'name_translations': {'en': 'Khrabrovo Airport'},
     'time_zone': 'Europe/Kaliningrad', 'flightable': 'true', 'coordinates': {'lat': 54.882656, 'lon': 20.586645},
     'name': 'Храброво', 'code': 'KGD', 'iata_type': 'airport', 'city_name': 'Калининград'},
    {'city_code': 'КЗЧ', 'country_code': 'RU', 'name_translations': {'en': 'Kazachinsk'}, 'time_zone': 'Asia/Irkutsk',
     'flightable': 'true', 'coordinates': {'lat': 56.268333, 'lon': 107.57333}, 'name': 'Казачинск', 'code': 'КЗЧ',
     'iata_type': 'airport', 'city_name': 'Казачинск'},
    {'city_code': 'GOJ', 'country_code': 'RU', 'name_translations': {'en': 'Nizhny Novgorod International Airport'},
     'time_zone': 'Europe/Moscow', 'flightable': 'true', 'coordinates': {'lat': 56.218613, 'lon': 43.789764},
     'name': 'Стригино', 'code': 'GOJ', 'iata_type': 'airport', 'city_name': 'Нижний Новгород'}]
