# Generated by Django 3.2 on 2022-06-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waysearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code_eng',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
