# Generated by Django 3.2 on 2022-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waysearch', '0002_city_code_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code_ICAO',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code_rus',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name_eng',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
