# Generated by Django 3.2 on 2022-07-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waysearch', '0003_auto_20220624_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
